### ISSUE TITLE
Lab 09 RMD Template being flagged as a malicious download

### ISSUE THREAD

**Issue by BissKuttner** [DS4PS/course_website#10]
I am trying to use the RMD template that is included in the Lab 9 instructions at https://ds4ps.github.io/Data-Science-Class/LABS//lab-09-instructions.html. My Norton software is flagging this as a "Malicious download" and won't let me get to it. 

Is there a way to reload that template or send it out a different way? Or does anyone else have a way that I can access it?

**Comment by lecy** [comment]
You can always find material on the course site if that happens:

https://github.com/DS4PS/Data-Science-Class

The template this week is just the basic version we have used on past labs:

https://github.com/DS4PS/Data-Science-Class/blob/master/TEMPLATES/MarkdownTemplateSimple.Rmd

**Comment by BissKuttner** [comment]
Thank you!

**Comment by lecy** [comment]
&#128077;
