### ISSUE TITLE
Lab-09 Part 3. Can't get variables to print

### ISSUE THREAD

**Issue by BissKuttner** [DS4PS/course_website#11]
## I am not sure what I am missing in my code for Lab-09 Part 3. I am not getting variables to print, just information about the variables is printing:

```{r, eval=F}
URL <- "https://data.tempe.gov/dataset/high-severity-traffic-crashes-1-08"
dat <- read.csv( URL )
str( dat )
```
## AND THIS IS THE OUTPUT:
'data.frame':	718 obs. of  1 variable:
 $ X..DOCTYPE.html.: Factor w/ 327 levels "'//www.google-analytics.com/analytics.js'",..: 281 282 283 280 246 175 300 297 299 295 ...

**Comment by BissKuttner** [comment]
I figured this out. I was using the wrong .url. It ought to have been
https://data.tempe.gov/dataset/7556b322-1b7d-4f65-87b8-598d11ef50fb/resource/6e542152-245b-4773-ba10-dc3223177e3b/download/crashdatareport.csv

**Comment by lecy** [comment]
Yeah, you need the link for the CSV file, not the landing page itself. It can be tricky to find the CSV link sometimes!
