### ISSUE TITLE
Discussion board - are we done with posting?

### ISSUE THREAD

**Issue by BissKuttner** [DS4PS/course_website#19]
Are we done with discussion board topics?
I don't see any topic listed for now or future dates.

**Comment by lecy** [comment]
I'm confused by this question - there should be topics posted:

https://ds4ps.github.io/course_website/assignments/#oct-30---nov-11--can-government-play-moneyball

**Comment by BissKuttner** [comment]
I see the new ones... I didnt see those before. The last one I saw was managing with data.
My bad :)

**Comment by lecy** [comment]
No problem! Just making sure my view wasn't different than yours ;-)
